"""changed name created_by_id -> owner_id

Revision ID: e9e62b340865
Revises: 52aba3f44df6
Create Date: 2026-04-07 04:26:12.804397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e62b340865'
down_revision: Union[str, Sequence[str], None] = '52aba3f44df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_groups_owner', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_groups_created_by', 'users', ['created_by_id'], ['id'])
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
